import { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { useSession } from 'next-auth/react';
import { Box, Flex, Grid, Link } from '@chakra-ui/react';

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid templateRows="auto 1fr auto" templateColumns="auto" minH="100vh">
        <Flex
          as="nav"
          position={'sticky'}
          top={0}
          left={0}
          right={0}
          wrap="wrap"
          justify="flex-end"
          align="center"
        >
          <Link
            href={'/api/auth/signin'}
            display={!!session ? 'none' : 'block'}
          >
            Sign In
          </Link>
          <Link
            href={'/api/auth/signout'}
            display={!!session ? 'block' : 'none'}
          >
            Sign Out
          </Link>
        </Flex>

        <Box as={'main'} className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </Box>

        <Box as={'footer'} className={styles.footer}></Box>
      </Grid>
    </div>
  );
};

export default Home;
